import { expect } from "chai"
import { Item, GildedRose } from "../app/gilded-rose"

describe("Gilded Rose Golden ", function () {

	it("Golden Ticket Test should succeed", function () {
		// (name, sellIn, quality)
		const gildedRose = new GildedRose([
			// Random Item
			new Item("foo0", 0, 0),
			new Item("foo0", 0, 0),
			new Item("foo1", 1, 0),
			new Item("foo1", 1, 1),
			new Item("foo1", 1, 5),
			new Item("foo1", 1, 50),
			new Item("foo2", 2, 0),
			new Item("foo2", 2, 1),
			new Item("foo2", 2, 5),
			new Item("foo2", 2, 50),
			new Item("foo3", 3, 0),
			new Item("foo3", 3, 1),
			new Item("foo3", 3, 5),
			new Item("foo3", 3, 50),
			new Item("foo10", 10, 0),
			new Item("foo10", 10, 1),
			new Item("foo10", 10, 5),
			new Item("foo10", 10, 50),
			new Item("foo11", 11, 0),
			new Item("foo11", 11, 1),
			new Item("foo11", 11, 5),
			new Item("foo11", 11, 50),
			new Item("foo50", 50, 0),
			new Item("foo50", 50, 1),
			new Item("foo50", 50, 5),
			new Item("foo50", 50, 50),
			new Item("fooMinus1", -1, 0),
			new Item("fooMinus1", -1, 1),
			new Item("fooMinus1", -1, 5),
			new Item("fooMinus1", -1, 50),
			new Item("fooMinus2", -2, 0),
			new Item("fooMinus2", -2, 1),
			new Item("fooMinus2", -2, 5),
			new Item("fooMinus2", -2, 50),
			// Aged Brie
			new Item("Aged Brie", 0, 0),
			new Item("Aged Brie", 0, 0),
			new Item("Aged Brie", 1, 0),
			new Item("Aged Brie", 1, 1),
			new Item("Aged Brie", 1, 5),
			new Item("Aged Brie", 1, 49),
			new Item("Aged Brie", 1, 50),
			new Item("Aged Brie", 2, 0),
			new Item("Aged Brie", 2, 1),
			new Item("Aged Brie", 2, 5),
			new Item("Aged Brie", 2, 50),
			new Item("Aged Brie", 3, 0),
			new Item("Aged Brie", 3, 1),
			new Item("Aged Brie", 3, 5),
			new Item("Aged Brie", 3, 50),
			new Item("Aged Brie", 10, 0),
			new Item("Aged Brie", 10, 1),
			new Item("Aged Brie", 10, 5),
			new Item("Aged Brie", 10, 50),
			new Item("Aged Brie", 11, 0),
			new Item("Aged Brie", 11, 1),
			new Item("Aged Brie", 11, 5),
			new Item("Aged Brie", 11, 50),
			new Item("Aged Brie", 50, 0),
			new Item("Aged Brie", 50, 1),
			new Item("Aged Brie", 50, 5),
			new Item("Aged Brie", 50, 50),
			new Item("Aged Brie", -1, 0),
			new Item("Aged Brie", -1, 1),
			new Item("Aged Brie", -1, 5),
			new Item("Aged Brie", -1, 50),
			new Item("Aged Brie", -2, 0),
			new Item("Aged Brie", -2, 1),
			new Item("Aged Brie", -2, 5),
			new Item("Aged Brie", -2, 50),
			// Backstage passes to a TAFKAL80ETC concert
			new Item("Backstage passes to a TAFKAL80ETC concert", 0, 0),
			new Item("Backstage passes to a TAFKAL80ETC concert", 0, 0),
			new Item("Backstage passes to a TAFKAL80ETC concert", 1, 0),
			new Item("Backstage passes to a TAFKAL80ETC concert", 1, 1),
			new Item("Backstage passes to a TAFKAL80ETC concert", 1, 5),
			new Item("Backstage passes to a TAFKAL80ETC concert", 1, 50),
			new Item("Backstage passes to a TAFKAL80ETC concert", 2, 0),
			new Item("Backstage passes to a TAFKAL80ETC concert", 2, 1),
			new Item("Backstage passes to a TAFKAL80ETC concert", 2, 5),
			new Item("Backstage passes to a TAFKAL80ETC concert", 2, 50),
			new Item("Backstage passes to a TAFKAL80ETC concert", 3, 0),
			new Item("Backstage passes to a TAFKAL80ETC concert", 3, 1),
			new Item("Backstage passes to a TAFKAL80ETC concert", 3, 5),
			new Item("Backstage passes to a TAFKAL80ETC concert", 3, 50),
			new Item("Backstage passes to a TAFKAL80ETC concert", 10, 0),
			new Item("Backstage passes to a TAFKAL80ETC concert", 10, 1),
			new Item("Backstage passes to a TAFKAL80ETC concert", 10, 5),
			new Item("Backstage passes to a TAFKAL80ETC concert", 10, 50),
			new Item("Backstage passes to a TAFKAL80ETC concert", 11, 0),
			new Item("Backstage passes to a TAFKAL80ETC concert", 11, 1),
			new Item("Backstage passes to a TAFKAL80ETC concert", 11, 5),
			new Item("Backstage passes to a TAFKAL80ETC concert", 11, 50),
			new Item("Backstage passes to a TAFKAL80ETC concert", 50, 0),
			new Item("Backstage passes to a TAFKAL80ETC concert", 50, 1),
			new Item("Backstage passes to a TAFKAL80ETC concert", 50, 5),
			new Item("Backstage passes to a TAFKAL80ETC concert", 50, 50),
			new Item("Backstage passes to a TAFKAL80ETC concert", -1, 0),
			new Item("Backstage passes to a TAFKAL80ETC concert", -1, 1),
			new Item("Backstage passes to a TAFKAL80ETC concert", -1, 5),
			new Item("Backstage passes to a TAFKAL80ETC concert", -1, 50),
			new Item("Backstage passes to a TAFKAL80ETC concert", -2, 0),
			new Item("Backstage passes to a TAFKAL80ETC concert", -2, 1),
			new Item("Backstage passes to a TAFKAL80ETC concert", -2, 5),
			new Item("Backstage passes to a TAFKAL80ETC concert", -2, 50),
			// Backstage passes to another concert (normal item)
			new Item("Backstage passes to another concert", 0, 0),
			new Item("Backstage passes to another concert", 0, 0),
			new Item("Backstage passes to another concert", 1, 0),
			new Item("Backstage passes to another concert", 1, 1),
			new Item("Backstage passes to another concert", 1, 5),
			new Item("Backstage passes to another concert", 1, 50),
			new Item("Backstage passes to another concert", 2, 0),
			new Item("Backstage passes to another concert", 2, 1),
			new Item("Backstage passes to another concert", 2, 5),
			new Item("Backstage passes to another concert", 2, 50),
			new Item("Backstage passes to another concert", 3, 0),
			new Item("Backstage passes to another concert", 3, 1),
			new Item("Backstage passes to another concert", 3, 5),
			new Item("Backstage passes to another concert", 3, 50),
			new Item("Backstage passes to another concert", 10, 0),
			new Item("Backstage passes to another concert", 10, 1),
			new Item("Backstage passes to another concert", 10, 5),
			new Item("Backstage passes to another concert", 10, 50),
			new Item("Backstage passes to another concert", 11, 0),
			new Item("Backstage passes to another concert", 11, 1),
			new Item("Backstage passes to another concert", 11, 5),
			new Item("Backstage passes to another concert", 11, 50),
			new Item("Backstage passes to another concert", 50, 0),
			new Item("Backstage passes to another concert", 50, 1),
			new Item("Backstage passes to another concert", 50, 5),
			new Item("Backstage passes to another concert", 50, 50),
			new Item("Backstage passes to another concert", -1, 0),
			new Item("Backstage passes to another concert", -1, 1),
			new Item("Backstage passes to another concert", -1, 5),
			new Item("Backstage passes to another concert", -1, 50),
			new Item("Backstage passes to another concert", -2, 0),
			new Item("Backstage passes to another concert", -2, 1),
			new Item("Backstage passes to another concert", -2, 5),
			new Item("Backstage passes to another concert", -2, 50),
			// Sulfuras, Hand of Ragnaros
			new Item("Sulfuras, Hand of Ragnaros", 0, 80),
			new Item("Sulfuras, Hand of Ragnaros", -1, 80),
			new Item("Sulfuras, Hand of Ragnaros", 1, 80),
			new Item("Sulfuras, Hand of Ragnaros", 5, 80),
			new Item("Sulfuras, Hand of Ragnaros", 50, 80),
			// Bad sulfuras (normal item)
			new Item("Sulfuras, Bad", 0, 0),
			new Item("Sulfuras, Bad", -1, 1),
			new Item("Sulfuras, Bad", 1, 5),
			new Item("Sulfuras, Bad", 5, 50),
		])
		const items = gildedRose.updateQuality()


		const expectedResult = [
			new Item("foo0", -1, 0),
			new Item("foo0", -1, 0),
			new Item("foo1", 0, 0),
			new Item("foo1", 0, 0),
			new Item("foo1", 0, 4),
			new Item("foo1", 0, 49),
			new Item("foo2", 1, 0),
			new Item("foo2", 1, 0),
			new Item("foo2", 1, 4),
			new Item("foo2", 1, 49),
			new Item("foo3", 2, 0),
			new Item("foo3", 2, 0),
			new Item("foo3", 2, 4),
			new Item("foo3", 2, 49),
			new Item("foo10", 9, 0),
			new Item("foo10", 9, 0),
			new Item("foo10", 9, 4),
			new Item("foo10", 9, 49),
			new Item("foo11", 10, 0),
			new Item("foo11", 10, 0),
			new Item("foo11", 10, 4),
			new Item("foo11", 10, 49),
			new Item("foo50", 49, 0),
			new Item("foo50", 49, 0),
			new Item("foo50", 49, 4),
			new Item("foo50", 49, 49),
			new Item("fooMinus1", -2, 0),
			new Item("fooMinus1", -2, 0),
			new Item("fooMinus1", -2, 3),
			new Item("fooMinus1", -2, 48),
			new Item("fooMinus2", -3, 0),
			new Item("fooMinus2", -3, 0),
			new Item("fooMinus2", -3, 3),
			new Item("fooMinus2", -3, 48),
			new Item("Aged Brie", -1, 2),
			new Item("Aged Brie", -1, 2),
			new Item("Aged Brie", 0, 1),
			new Item("Aged Brie", 0, 2),
			new Item("Aged Brie", 0, 6),
			new Item("Aged Brie", 0, 50),
			new Item("Aged Brie", 0, 50),
			new Item("Aged Brie", 1, 1),
			new Item("Aged Brie", 1, 2),
			new Item("Aged Brie", 1, 6),
			new Item("Aged Brie", 1, 50),
			new Item("Aged Brie", 2, 1),
			new Item("Aged Brie", 2, 2),
			new Item("Aged Brie", 2, 6),
			new Item("Aged Brie", 2, 50),
			new Item("Aged Brie", 9, 1),
			new Item("Aged Brie", 9, 2),
			new Item("Aged Brie", 9, 6),
			new Item("Aged Brie", 9, 50),
			new Item("Aged Brie", 10, 1),
			new Item("Aged Brie", 10, 2),
			new Item("Aged Brie", 10, 6),
			new Item("Aged Brie", 10, 50),
			new Item("Aged Brie", 49, 1),
			new Item("Aged Brie", 49, 2),
			new Item("Aged Brie", 49, 6),
			new Item("Aged Brie", 49, 50),
			new Item("Aged Brie", -2, 2),
			new Item("Aged Brie", -2, 3),
			new Item("Aged Brie", -2, 7),
			new Item("Aged Brie", -2, 50),
			new Item("Aged Brie", -3, 2),
			new Item("Aged Brie", -3, 3),
			new Item("Aged Brie", -3, 7),
			new Item("Aged Brie", -3, 50),
			new Item("Backstage passes to a TAFKAL80ETC concert", -1, 0),
			new Item("Backstage passes to a TAFKAL80ETC concert", -1, 0),
			new Item("Backstage passes to a TAFKAL80ETC concert", 0, 3),
			new Item("Backstage passes to a TAFKAL80ETC concert", 0, 4),
			new Item("Backstage passes to a TAFKAL80ETC concert", 0, 8),
			new Item("Backstage passes to a TAFKAL80ETC concert", 0, 50),
			new Item("Backstage passes to a TAFKAL80ETC concert", 1, 3),
			new Item("Backstage passes to a TAFKAL80ETC concert", 1, 4),
			new Item("Backstage passes to a TAFKAL80ETC concert", 1, 8),
			new Item("Backstage passes to a TAFKAL80ETC concert", 1, 50),
			new Item("Backstage passes to a TAFKAL80ETC concert", 2, 3),
			new Item("Backstage passes to a TAFKAL80ETC concert", 2, 4),
			new Item("Backstage passes to a TAFKAL80ETC concert", 2, 8),
			new Item("Backstage passes to a TAFKAL80ETC concert", 2, 50),
			new Item("Backstage passes to a TAFKAL80ETC concert", 9, 2),
			new Item("Backstage passes to a TAFKAL80ETC concert", 9, 3),
			new Item("Backstage passes to a TAFKAL80ETC concert", 9, 7),
			new Item("Backstage passes to a TAFKAL80ETC concert", 9, 50),
			new Item("Backstage passes to a TAFKAL80ETC concert", 10, 1),
			new Item("Backstage passes to a TAFKAL80ETC concert", 10, 2),
			new Item("Backstage passes to a TAFKAL80ETC concert", 10, 6),
			new Item("Backstage passes to a TAFKAL80ETC concert", 10, 50),
			new Item("Backstage passes to a TAFKAL80ETC concert", 49, 1),
			new Item("Backstage passes to a TAFKAL80ETC concert", 49, 2),
			new Item("Backstage passes to a TAFKAL80ETC concert", 49, 6),
			new Item("Backstage passes to a TAFKAL80ETC concert", 49, 50),
			new Item("Backstage passes to a TAFKAL80ETC concert", -2, 0),
			new Item("Backstage passes to a TAFKAL80ETC concert", -2, 0),
			new Item("Backstage passes to a TAFKAL80ETC concert", -2, 0),
			new Item("Backstage passes to a TAFKAL80ETC concert", -2, 0),
			new Item("Backstage passes to a TAFKAL80ETC concert", -3, 0),
			new Item("Backstage passes to a TAFKAL80ETC concert", -3, 0),
			new Item("Backstage passes to a TAFKAL80ETC concert", -3, 0),
			new Item("Backstage passes to a TAFKAL80ETC concert", -3, 0),
			new Item("Backstage passes to another concert", -1, 0),
			new Item("Backstage passes to another concert", -1, 0),
			new Item("Backstage passes to another concert", 0, 0),
			new Item("Backstage passes to another concert", 0, 0),
			new Item("Backstage passes to another concert", 0, 4),
			new Item("Backstage passes to another concert", 0, 49),
			new Item("Backstage passes to another concert", 1, 0),
			new Item("Backstage passes to another concert", 1, 0),
			new Item("Backstage passes to another concert", 1, 4),
			new Item("Backstage passes to another concert", 1, 49),
			new Item("Backstage passes to another concert", 2, 0),
			new Item("Backstage passes to another concert", 2, 0),
			new Item("Backstage passes to another concert", 2, 4),
			new Item("Backstage passes to another concert", 2, 49),
			new Item("Backstage passes to another concert", 9, 0),
			new Item("Backstage passes to another concert", 9, 0),
			new Item("Backstage passes to another concert", 9, 4),
			new Item("Backstage passes to another concert", 9, 49),
			new Item("Backstage passes to another concert", 10, 0),
			new Item("Backstage passes to another concert", 10, 0),
			new Item("Backstage passes to another concert", 10, 4),
			new Item("Backstage passes to another concert", 10, 49),
			new Item("Backstage passes to another concert", 49, 0),
			new Item("Backstage passes to another concert", 49, 0),
			new Item("Backstage passes to another concert", 49, 4),
			new Item("Backstage passes to another concert", 49, 49),
			new Item("Backstage passes to another concert", -2, 0),
			new Item("Backstage passes to another concert", -2, 0),
			new Item("Backstage passes to another concert", -2, 3),
			new Item("Backstage passes to another concert", -2, 48),
			new Item("Backstage passes to another concert", -3, 0),
			new Item("Backstage passes to another concert", -3, 0),
			new Item("Backstage passes to another concert", -3, 3),
			new Item("Backstage passes to another concert", -3, 48),
			new Item("Sulfuras, Hand of Ragnaros", 0, 80),
			new Item("Sulfuras, Hand of Ragnaros", -1, 80),
			new Item("Sulfuras, Hand of Ragnaros", 1, 80),
			new Item("Sulfuras, Hand of Ragnaros", 5, 80),
			new Item("Sulfuras, Hand of Ragnaros", 50, 80),
			new Item("Sulfuras, Bad", -1, 0),
			new Item("Sulfuras, Bad", -2, 0),
			new Item("Sulfuras, Bad", 0, 4),
			new Item("Sulfuras, Bad", 4, 49),
		]
		expect(items).deep.equal(expectedResult)
	})
})
